<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use JsonException;
use RuntimeException;

final class MenuLoadTestDataCommand extends Command
{
    private const SORT_ORDER_OFFSET = 900000;

    private const LOAD_TEST_SOURCE = 'menu:load-test-data';

    /**
     * @var list<string>
     */
    private const DEMO_TENANT_SLUGS = [
        'arat-riverside',
        'northstar-bistro',
    ];

    /**
     * @var list<string>
     */
    private const EN_ADJECTIVES = [
        'Bright',
        'Smoked',
        'Market',
        'Crisp',
        'Garden',
        'Golden',
        'Fresh',
        'Charcoal',
    ];

    /**
     * @var list<string>
     */
    private const EN_NOUNS = [
        'Trout',
        'Chicken',
        'Lentil',
        'Mushroom',
        'Pepper',
        'Cheese',
        'Potato',
        'Eggplant',
    ];

    /**
     * @var list<string>
     */
    private const HY_ADJECTIVES = [
        'Պայծառ',
        'Ապխտած',
        'Շուկայի',
        'Խրթխրթան',
        'Այգու',
        'Ոսկեգույն',
        'Թարմ',
        'Ածուխի',
    ];

    /**
     * @var list<string>
     */
    private const HY_NOUNS = [
        'իշխան',
        'հավ',
        'ոսպ',
        'սունկ',
        'պղպեղ',
        'պանիր',
        'կարտոֆիլ',
        'սմբուկ',
    ];

    /**
     * @var list<string>
     */
    private const RU_ADJECTIVES = [
        'Яркий',
        'Копчёный',
        'Рыночный',
        'Хрустящий',
        'Садовый',
        'Золотой',
        'Свежий',
        'Угольный',
    ];

    /**
     * @var list<string>
     */
    private const RU_NOUNS = [
        'форель',
        'курица',
        'чечевица',
        'грибы',
        'перец',
        'сыр',
        'картофель',
        'баклажан',
    ];

    protected $signature = 'menu:load-test-data
        {--seed=smartrest-menu-load-v1 : Deterministic seed label for generated names and marker keys}
        {--categories=200 : Approximate category rows per demo tenant}
        {--items=20000 : Menu item rows per demo tenant}
        {--batch=1000 : Insert batch size}
        {--purge-generated : Delete rows generated by this command before loading}
        {--purge-only : Delete rows generated by this command and exit without loading}';

    protected $description = 'Generate deterministic Menu load-test rows for existing demo tenants.';

    public function handle(): int
    {
        if (! app()->environment(['local', 'testing'])) {
            $this->error('Refusing to run outside local/testing environments.');

            return self::FAILURE;
        }

        DB::disableQueryLog();
        @set_time_limit(0);

        $seed = trim((string) $this->option('seed'));

        if ($seed === '') {
            $this->error('--seed must be a non-empty string.');

            return self::FAILURE;
        }

        $categoryCount = $this->positiveIntOption('categories');
        $itemCount = $this->positiveIntOption('items');
        $batch = $this->positiveIntOption('batch');
        $loadTestKey = $this->loadTestKey($seed);
        $startedAt = microtime(true);

        if ($categoryCount < 2) {
            $this->error('--categories must be at least 2 so generated items can belong to subcategories.');

            return self::FAILURE;
        }

        if ((bool) $this->option('purge-generated') || (bool) $this->option('purge-only')) {
            $purged = $this->purgeGeneratedRows();
            $this->line(sprintf(
                'Purged generated rows: menu_items=%d, menu_categories=%d.',
                $purged['menu_items'],
                $purged['menu_categories'],
            ));
        }

        if ((bool) $this->option('purge-only')) {
            $this->info('menu:load-test-data purge complete.');

            return self::SUCCESS;
        }

        $existing = $this->existingGeneratedCounts();

        if ($existing['menu_categories'] > 0 || $existing['menu_items'] > 0) {
            $this->error(sprintf(
                'Generated Menu load-test rows already exist: menu_categories=%d, menu_items=%d. Re-run with --purge-generated to replace them, or --purge-only to remove them.',
                $existing['menu_categories'],
                $existing['menu_items'],
            ));

            return self::FAILURE;
        }

        $tenants = $this->demoTenants();
        $this->line('menu:load-test-data plan');
        $this->line('seed: '.$seed);
        $this->line('load_test_key: '.$loadTestKey);
        $this->line('demo_tenants: '.implode(', ', array_column($tenants, 'slug')));
        $this->line('categories_per_tenant: '.$categoryCount);
        $this->line('items_per_tenant: '.$itemCount);
        $this->line('batch: '.$batch);

        $categoryRows = $this->insertCategories($tenants, $categoryCount, $batch, $seed, $loadTestKey);
        $itemRows = $this->insertItems($tenants, $itemCount, $batch, $seed, $loadTestKey);
        $this->reportTenantCounts($tenants, $loadTestKey);

        $this->info(sprintf(
            'menu:load-test-data complete: menu_categories=%d, menu_items=%d, elapsed_seconds=%s.',
            $categoryRows,
            $itemRows,
            number_format(microtime(true) - $startedAt, 3, '.', ''),
        ));

        return self::SUCCESS;
    }

    private function positiveIntOption(string $name): int
    {
        $value = filter_var($this->option($name), FILTER_VALIDATE_INT);

        if (! is_int($value) || $value < 1) {
            throw new RuntimeException("--{$name} must be a positive integer.");
        }

        return $value;
    }

    private function loadTestKey(string $seed): string
    {
        return self::LOAD_TEST_SOURCE.':'.substr(sha1($seed), 0, 16);
    }

    /**
     * @return array{menu_categories: int, menu_items: int}
     */
    private function existingGeneratedCounts(): array
    {
        return [
            'menu_categories' => DB::table('menu_categories')->whereNotNull('load_test_key')->count(),
            'menu_items' => DB::table('menu_items')->whereNotNull('load_test_key')->count(),
        ];
    }

    /**
     * @return array{menu_categories: int, menu_items: int}
     */
    private function purgeGeneratedRows(): array
    {
        $itemCount = DB::table('menu_items')->whereNotNull('load_test_key')->delete();

        $childCount = DB::table('menu_categories')
            ->whereNotNull('load_test_key')
            ->whereNotNull('parent_id')
            ->delete();
        $rootCount = DB::table('menu_categories')
            ->whereNotNull('load_test_key')
            ->delete();

        return [
            'menu_categories' => $childCount + $rootCount,
            'menu_items' => $itemCount,
        ];
    }

    /**
     * @return list<array{id: int, slug: string, currency: string, branches: list<array{id: int, name: string}>}>
     */
    private function demoTenants(): array
    {
        $tenants = DB::table('tenants')
            ->whereIn('slug', self::DEMO_TENANT_SLUGS)
            ->select(['id', 'slug', 'currency'])
            ->get()
            ->keyBy('slug');

        foreach (self::DEMO_TENANT_SLUGS as $slug) {
            if (! $tenants->has($slug)) {
                throw new RuntimeException("Missing demo tenant [{$slug}]. Run make fresh before generating load-test data.");
            }
        }

        $demoTenants = [];

        foreach (self::DEMO_TENANT_SLUGS as $slug) {
            $tenant = $tenants->get($slug);
            assert($tenant !== null);
            $tenantId = $this->intDatabaseValue($tenant->id, 'tenant id');
            $tenantSlug = $this->stringDatabaseValue($tenant->slug, 'tenant slug');
            $currency = $this->stringDatabaseValue($tenant->currency, 'tenant currency');
            $branches = DB::table('branches')
                ->where('tenant_id', $tenantId)
                ->where('status', 'active')
                ->orderBy('id')
                ->select(['id', 'name'])
                ->get();

            if ($branches->isEmpty()) {
                throw new RuntimeException("Demo tenant [{$slug}] has no active branches.");
            }

            $branchRows = [];

            foreach ($branches as $branch) {
                $branchRows[] = [
                    'id' => $this->intDatabaseValue($branch->id, 'branch id'),
                    'name' => $this->stringDatabaseValue($branch->name, 'branch name'),
                ];
            }

            $demoTenants[] = [
                'id' => $tenantId,
                'slug' => $tenantSlug,
                'currency' => $currency,
                'branches' => $branchRows,
            ];
        }

        return $demoTenants;
    }

    /**
     * @param  list<array{id: int, slug: string, currency: string}>  $tenants
     */
    private function insertCategories(array $tenants, int $categoryCount, int $batch, string $seed, string $loadTestKey): int
    {
        [$rootCount, $subcategoriesPerRoot, $remainder] = $this->categoryShape($categoryCount);
        $timestamp = now();
        $rootRows = [];

        foreach ($tenants as $tenant) {
            for ($root = 1; $root <= $rootCount; $root++) {
                $rootRows[] = [
                    'tenant_id' => $tenant['id'],
                    'parent_id' => null,
                    'archived_with_category_id' => null,
                    'translated_name' => $this->localizedName($seed, 'Root', $tenant['slug'], $root),
                    'sort_order' => self::SORT_ORDER_OFFSET + $root,
                    'active' => true,
                    'load_test_key' => $loadTestKey,
                    'deleted_at' => null,
                    'created_at' => $timestamp,
                    'updated_at' => $timestamp,
                ];
            }
        }

        $this->insertRows('menu_categories', $rootRows, $batch);
        $rootIds = $this->rootIds($loadTestKey);
        $subcategoryRows = [];

        foreach ($tenants as $tenant) {
            for ($root = 1; $root <= $rootCount; $root++) {
                $tenantRootSubcategoryCount = $subcategoriesPerRoot + ($root <= $remainder ? 1 : 0);
                $rootId = $rootIds[$tenant['id']][$root] ?? null;

                if (! is_int($rootId)) {
                    throw new RuntimeException('Unable to resolve generated root category ids.');
                }

                for ($subcategory = 1; $subcategory <= $tenantRootSubcategoryCount; $subcategory++) {
                    $subcategoryRows[] = [
                        'tenant_id' => $tenant['id'],
                        'parent_id' => $rootId,
                        'archived_with_category_id' => null,
                        'translated_name' => $this->localizedName($seed, 'Category', $tenant['slug'], $root, $subcategory),
                        'sort_order' => self::SORT_ORDER_OFFSET + $subcategory,
                        'active' => true,
                        'load_test_key' => $loadTestKey,
                        'deleted_at' => null,
                        'created_at' => $timestamp,
                        'updated_at' => $timestamp,
                    ];
                }
            }
        }

        $this->insertRows('menu_categories', $subcategoryRows, $batch);

        return count($rootRows) + count($subcategoryRows);
    }

    /**
     * @return array{0: int, 1: int, 2: int}
     */
    private function categoryShape(int $categoryCount): array
    {
        $rootCount = min(20, max(1, intdiv($categoryCount, 10)));
        $subcategoryCount = max(0, $categoryCount - $rootCount);
        $subcategoriesPerRoot = intdiv($subcategoryCount, $rootCount);
        $remainder = $subcategoryCount % $rootCount;

        return [$rootCount, $subcategoriesPerRoot, $remainder];
    }

    /**
     * @return array<int, array<int, int>>
     */
    private function rootIds(string $loadTestKey): array
    {
        $rootIds = [];

        DB::table('menu_categories')
            ->where('load_test_key', $loadTestKey)
            ->whereNull('parent_id')
            ->select(['id', 'tenant_id', 'sort_order'])
            ->orderBy('id')
            ->chunkById(500, function ($roots) use (&$rootIds): void {
                foreach ($roots as $root) {
                    $tenantId = $this->intDatabaseValue($root->tenant_id, 'root tenant id');
                    $rootNumber = $this->intDatabaseValue($root->sort_order, 'root sort order') - self::SORT_ORDER_OFFSET;
                    $rootIds[$tenantId][$rootNumber] = $this->intDatabaseValue($root->id, 'root id');
                }
            });

        return $rootIds;
    }

    /**
     * @param  list<array{id: int, slug: string, currency: string, branches: list<array{id: int, name: string}>}>  $tenants
     */
    private function insertItems(array $tenants, int $itemCount, int $batch, string $seed, string $loadTestKey): int
    {
        $timestamp = now();
        $inserted = 0;

        foreach ($tenants as $tenant) {
            $categoryIds = DB::table('menu_categories')
                ->where('tenant_id', $tenant['id'])
                ->where('load_test_key', $loadTestKey)
                ->whereNotNull('parent_id')
                ->orderBy('parent_id')
                ->orderBy('sort_order')
                ->pluck('id')
                ->map(fn (mixed $id): int => $this->intDatabaseValue($id, 'subcategory id'))
                ->values();

            if ($categoryIds->isEmpty()) {
                throw new RuntimeException("Generated tenant [{$tenant['slug']}] has no load-test subcategories.");
            }

            $branches = $tenant['branches'];
            $branchCount = count($branches);
            $baseItemsPerBranch = intdiv($itemCount, $branchCount);
            $branchRemainder = $itemCount % $branchCount;

            foreach ($branches as $branchIndex => $branch) {
                $rows = [];
                $itemsForBranch = $baseItemsPerBranch + ($branchIndex < $branchRemainder ? 1 : 0);

                for ($item = 1; $item <= $itemsForBranch; $item++) {
                    $globalItem = $inserted + $item;
                    $categoryId = $categoryIds[($item - 1) % $categoryIds->count()];
                    $rows[] = [
                        'tenant_id' => $tenant['id'],
                        'branch_id' => $branch['id'],
                        'category_id' => $categoryId,
                        'translated_name' => $this->localizedName($seed, 'Dish', $tenant['slug'], $branchIndex + 1, $item),
                        'translated_description' => $this->localizedDescription($seed, $tenant['slug'], $branchIndex + 1, $item),
                        'internal_image' => null,
                        'public_image' => null,
                        'price_minor' => $this->priceMinor($tenant['currency'], $tenant['id'], $branchIndex + 1, $item),
                        'currency' => $tenant['currency'],
                        'sort_order' => self::SORT_ORDER_OFFSET + $item,
                        'active' => $item % 19 !== 0,
                        'load_test_key' => $loadTestKey,
                        'archived_with_category_id' => null,
                        'deleted_at' => null,
                        'created_at' => $timestamp,
                        'updated_at' => $timestamp,
                    ];

                    if (count($rows) >= $batch) {
                        $this->insertRows('menu_items', $rows, $batch);
                        $rows = [];
                    }
                }

                if ($rows !== []) {
                    $this->insertRows('menu_items', $rows, $batch);
                }

                $inserted += $itemsForBranch;
            }
        }

        return $inserted;
    }

    /**
     * @param  list<array<string, mixed>>  $rows
     */
    private function insertRows(string $table, array $rows, int $batch): void
    {
        if ($batch < 1) {
            throw new RuntimeException('Batch size must be positive.');
        }

        /** @var int<1, max> $positiveBatch */
        $positiveBatch = $batch;

        foreach (array_chunk($rows, $positiveBatch) as $chunk) {
            DB::table($table)->insert($chunk);
        }
    }

    /**
     * @throws JsonException
     */
    private function localizedName(string $seed, string $kind, string $tenantSlug, int $first, ?int $second = null): string
    {
        $hash = (int) sprintf('%u', crc32($seed.'|'.$kind.'|'.$tenantSlug.'|'.$first.'|'.($second ?? 0)));
        $number = $second === null ? (string) $first : "{$first}-{$second}";

        return json_encode([
            'hy' => self::HY_ADJECTIVES[$hash % count(self::HY_ADJECTIVES)].' '.self::HY_NOUNS[intdiv($hash, 5) % count(self::HY_NOUNS)]." {$this->armenianKind($kind)} {$tenantSlug} {$number}",
            'ru' => self::RU_ADJECTIVES[$hash % count(self::RU_ADJECTIVES)].' '.self::RU_NOUNS[intdiv($hash, 5) % count(self::RU_NOUNS)]." {$this->russianKind($kind)} {$tenantSlug} {$number}",
            'en' => self::EN_ADJECTIVES[$hash % count(self::EN_ADJECTIVES)].' '.self::EN_NOUNS[intdiv($hash, 5) % count(self::EN_NOUNS)]." {$kind} {$tenantSlug} {$number}",
        ], JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    }

    /**
     * @throws JsonException
     */
    private function localizedDescription(string $seed, string $tenantSlug, int $branch, int $item): string
    {
        return json_encode([
            'hy' => "Բեռնման թեստ {$seed} {$tenantSlug} {$branch}-{$item}",
            'ru' => "Нагрузочный тест {$seed} {$tenantSlug} {$branch}-{$item}",
            'en' => "Load test {$seed} {$tenantSlug} {$branch}-{$item}",
        ], JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    }

    private function armenianKind(string $kind): string
    {
        return match ($kind) {
            'Root' => 'մենյու',
            'Category' => 'բաժին',
            'Dish' => 'ուտեստ',
            default => $kind,
        };
    }

    private function russianKind(string $kind): string
    {
        return match ($kind) {
            'Root' => 'меню',
            'Category' => 'раздел',
            'Dish' => 'блюдо',
            default => $kind,
        };
    }

    private function priceMinor(string $currency, int $tenantId, int $branch, int $item): int
    {
        $spread = ($tenantId * 17 + $branch * 31 + $item * 43) % 700;

        return $currency === 'USD'
            ? 500 + $spread
            : 80000 + ($spread * 1000);
    }

    /**
     * @param  list<array{id: int, slug: string}>  $tenants
     */
    private function reportTenantCounts(array $tenants, string $loadTestKey): void
    {
        foreach ($tenants as $tenant) {
            $categoryCount = DB::table('menu_categories')
                ->where('tenant_id', $tenant['id'])
                ->where('load_test_key', $loadTestKey)
                ->count();
            $itemCount = DB::table('menu_items')
                ->where('tenant_id', $tenant['id'])
                ->where('load_test_key', $loadTestKey)
                ->count();

            $this->line(sprintf(
                'tenant=%s menu_categories=%d menu_items=%d',
                $tenant['slug'],
                $categoryCount,
                $itemCount,
            ));
        }
    }

    private function intDatabaseValue(mixed $value, string $name): int
    {
        if (is_int($value)) {
            return $value;
        }

        if (is_string($value) && $value !== '') {
            return (int) $value;
        }

        throw new RuntimeException("Invalid integer database value for {$name}.");
    }

    private function stringDatabaseValue(mixed $value, string $name): string
    {
        if (is_string($value) && $value !== '') {
            return $value;
        }

        throw new RuntimeException("Invalid string database value for {$name}.");
    }
}
