<?php

declare(strict_types=1);

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;

uses(RefreshDatabase::class);

afterEach(function (): void {
    app()->detectEnvironment(fn (): string => 'testing');
});

it('refuses to run outside local and testing environments', function (): void {
    menuLoadTestDemoTenant('arat-riverside', 'AMD', ['Arat Kentron']);
    menuLoadTestDemoTenant('northstar-bistro', 'USD', ['Northstar Downtown']);
    app()->detectEnvironment(fn (): string => 'production');

    $this->artisan('menu:load-test-data', [
        '--categories' => 2,
        '--items' => 2,
    ])
        ->expectsOutput('Refusing to run outside local/testing environments.')
        ->assertFailed();
});

it('generates deterministic load rows for both demo tenants and refuses duplicates', function (): void {
    $arat = menuLoadTestDemoTenant('arat-riverside', 'AMD', ['Arat Kentron', 'Arat Dilijan']);
    $northstar = menuLoadTestDemoTenant('northstar-bistro', 'USD', ['Northstar Downtown']);
    menuLoadTestDemoMenuRow($arat['tenant_id'], $arat['branch_ids'][0]);

    $this->artisan('menu:load-test-data', [
        '--seed' => 'tiny-seed',
        '--categories' => 6,
        '--items' => 12,
        '--batch' => 3,
    ])
        ->expectsOutputToContain('menu:load-test-data complete')
        ->assertSuccessful();

    expect(DB::table('menu_categories')->where('tenant_id', $arat['tenant_id'])->whereNotNull('load_test_key')->count())->toBe(6)
        ->and(DB::table('menu_categories')->where('tenant_id', $northstar['tenant_id'])->whereNotNull('load_test_key')->count())->toBe(6)
        ->and(DB::table('menu_items')->where('tenant_id', $arat['tenant_id'])->whereNotNull('load_test_key')->count())->toBe(12)
        ->and(DB::table('menu_items')->where('tenant_id', $northstar['tenant_id'])->whereNotNull('load_test_key')->count())->toBe(12)
        ->and(DB::table('menu_items')->where('tenant_id', $arat['tenant_id'])->where('branch_id', $arat['branch_ids'][0])->whereNotNull('load_test_key')->count())->toBe(6)
        ->and(DB::table('menu_items')->where('tenant_id', $arat['tenant_id'])->where('branch_id', $arat['branch_ids'][1])->whereNotNull('load_test_key')->count())->toBe(6)
        ->and(DB::table('menu_items')->whereNull('load_test_key')->count())->toBe(1);

    $generatedItem = DB::table('menu_items')
        ->where('tenant_id', $northstar['tenant_id'])
        ->whereNotNull('load_test_key')
        ->first();

    expect($generatedItem)->not->toBeNull()
        ->and(json_decode((string) $generatedItem->translated_name, true, flags: JSON_THROW_ON_ERROR))->toHaveKeys(['hy', 'ru', 'en'])
        ->and((int) $generatedItem->price_minor)->toBeGreaterThan(0)
        ->and((string) $generatedItem->currency)->toBe('USD')
        ->and((string) $generatedItem->load_test_key)->toStartWith('menu:load-test-data:');

    $this->artisan('menu:load-test-data', [
        '--seed' => 'tiny-seed',
        '--categories' => 6,
        '--items' => 12,
    ])
        ->expectsOutputToContain('Generated Menu load-test rows already exist')
        ->assertFailed();

    expect(DB::table('menu_items')->whereNotNull('load_test_key')->count())->toBe(24);
});

it('purges only rows generated by the load-test command', function (): void {
    $arat = menuLoadTestDemoTenant('arat-riverside', 'AMD', ['Arat Kentron']);
    menuLoadTestDemoTenant('northstar-bistro', 'USD', ['Northstar Downtown']);
    $demo = menuLoadTestDemoMenuRow($arat['tenant_id'], $arat['branch_ids'][0]);

    $this->artisan('menu:load-test-data', [
        '--categories' => 4,
        '--items' => 8,
    ])->assertSuccessful();

    $this->artisan('menu:load-test-data', [
        '--purge-only' => true,
    ])
        ->expectsOutputToContain('Purged generated rows')
        ->assertSuccessful();

    expect(DB::table('menu_categories')->whereNotNull('load_test_key')->count())->toBe(0)
        ->and(DB::table('menu_items')->whereNotNull('load_test_key')->count())->toBe(0)
        ->and(DB::table('menu_categories')->where('id', $demo['root_id'])->exists())->toBeTrue()
        ->and(DB::table('menu_categories')->where('id', $demo['category_id'])->exists())->toBeTrue()
        ->and(DB::table('menu_items')->where('id', $demo['item_id'])->exists())->toBeTrue();
});

/**
 * @param  list<string>  $branches
 * @return array{tenant_id: int, branch_ids: list<int>}
 */
function menuLoadTestDemoTenant(string $slug, string $currency, array $branches): array
{
    $now = now();
    $tenantId = (int) DB::table('tenants')->insertGetId([
        'name' => str($slug)->headline()->toString(),
        'slug' => $slug,
        'default_locale' => $currency === 'USD' ? 'en' : 'hy',
        'currency' => $currency,
        'status' => 'active',
        'created_at' => $now,
        'updated_at' => $now,
    ]);
    $branchIds = [];

    foreach ($branches as $branch) {
        $branchIds[] = (int) DB::table('branches')->insertGetId([
            'tenant_id' => $tenantId,
            'name' => $branch,
            'timezone' => 'Asia/Yerevan',
            'status' => 'active',
            'created_at' => $now,
            'updated_at' => $now,
        ]);
    }

    return [
        'tenant_id' => $tenantId,
        'branch_ids' => $branchIds,
    ];
}

/**
 * @return array{root_id: int, category_id: int, item_id: int}
 */
function menuLoadTestDemoMenuRow(int $tenantId, int $branchId): array
{
    $now = now();
    $rootId = (int) DB::table('menu_categories')->insertGetId([
        'tenant_id' => $tenantId,
        'parent_id' => null,
        'archived_with_category_id' => null,
        'translated_name' => json_encode(['hy' => 'Մենյու', 'ru' => 'Меню', 'en' => 'Menu'], JSON_THROW_ON_ERROR),
        'sort_order' => 1,
        'active' => true,
        'load_test_key' => null,
        'deleted_at' => null,
        'created_at' => $now,
        'updated_at' => $now,
    ]);
    $categoryId = (int) DB::table('menu_categories')->insertGetId([
        'tenant_id' => $tenantId,
        'parent_id' => $rootId,
        'archived_with_category_id' => null,
        'translated_name' => json_encode(['hy' => 'Նախաճաշ', 'ru' => 'Завтрак', 'en' => 'Breakfast'], JSON_THROW_ON_ERROR),
        'sort_order' => 2,
        'active' => true,
        'load_test_key' => null,
        'deleted_at' => null,
        'created_at' => $now,
        'updated_at' => $now,
    ]);
    $itemId = (int) DB::table('menu_items')->insertGetId([
        'tenant_id' => $tenantId,
        'branch_id' => $branchId,
        'category_id' => $categoryId,
        'translated_name' => json_encode(['hy' => 'Ձվածեղ', 'ru' => 'Омлет', 'en' => 'Omelette'], JSON_THROW_ON_ERROR),
        'translated_description' => null,
        'internal_image' => null,
        'public_image' => null,
        'price_minor' => 120000,
        'currency' => 'AMD',
        'sort_order' => 1,
        'active' => true,
        'load_test_key' => null,
        'archived_with_category_id' => null,
        'deleted_at' => null,
        'created_at' => $now,
        'updated_at' => $now,
    ]);

    return [
        'root_id' => $rootId,
        'category_id' => $categoryId,
        'item_id' => $itemId,
    ];
}
